services:
  postgres:
    image: postgres:18
    container_name: postgresMechWorkshop
    restart: 'always'
    ports:
      - '5455:5432'
    environment:
      POSTGRES_USER: workshop
      POSTGRES_PASSWORD: workshop123
      POSTGRES_DB: workshopdb
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8.6
    container_name: redisMechWorkshop
    restart: 'always'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
